<h1 class="page-title"> Stranice
    <small> Menadžment stranica</small>
    <div class="btn-group pull-right">
        <a href="<?php echo $this->resourceUrl()->action('create');?>" class="btn sbold green"> Dodaj novu &nbsp;
            <i class="fa fa-plus"></i>
        </a>
    </div>
</h1>

<div class="row">
    <div class="col-md-12">
        <div class="portlet light bordered">
            <div class="portlet-title">
                <div class="caption font-dark">
                    <i class="icon-layers font-dark"></i>
                    <span class="caption-subject bold uppercase"> Lista stranica</span>
                </div>
            </div>
            <div class="portlet-body">
                <table class="table table-striped table-bordered table-hover table-checkable order-column" id="datatable">
                    <thead>
                    <tr>
                        <th>
                            Fotografija
                        </th>
                        <?php foreach ($this->languages as $language): ?>
                            <th>
                                <?php echo $language['name'];?>
                            </th>
                        <?php endforeach; ?>
                        <th  class="text-center">
                            Status
                        </th>
                        <th class="text-center" style="width:1%;">Akcije</th>
                    </tr>
                    </thead>
                    <tbody>
                    <?php foreach ($this->pages as $page):?>
                        <tr class="odd-gradeX">
                            <?php foreach ($this->languages as $language):
                                $exist = FALSE;
                                if (count($this->pagecontent[$page['id']]) > 0):
                                    foreach ($this->pagecontent[$page['id']] as $content):
                                        if ($content['language_id'] == $language['id']):
                                            $exist = TRUE;
                                            if ($content['page_id'] == $page['id'] && $language['priority'] == 1):?>
                                                <td style="width: 10%;">
                                                    <img src="<?php echo $content['page_photo'];?>" style="width: 70%;"/>
                                                </td>
                                            <?php endif; ?>
                                            <td>
                                                <?php echo $content['title'];?>
                                            </td>
                                        <?php endif; ?>
                                    <?php endforeach;?>
                                    <?php if (!$exist): ?>
                                    <td>
                                        Nema sadržaja.
                                    </td>
                                <?php endif; ?>
                                <?php endif; ?>
                            <?php endforeach; ?>
                            <td class="text-center">
                                <?php if ($page['status'] == Model_Admin_Page_Page::STATUS_VISIBLE):?>
                                    <span class="label label-sm label-info" style="background-color: #8775a7;"> Vidljivo </span>
                                <?php else:?>
                                    <span class="label label-sm label-danger label-info" style="background-color: #8775a7;"> Sakriveno </span>
                                <?php endif; ?>
                            </td>
                            <td class="text-center" style="width: 15%;">
                                <a href="<?php echo $this->url(array('controller' => 'admin_page', 'action' => 'edit', 'page' => $page['id'], 'language' => 1),'default', true);?>"
                                   class="btn btn-ucms btn-sm" type="button">
                                    <i class="icon-pencil"></i>
                                </a>
                                <?php if ($page['status'] == 1):?>
                                    <a class="btn btn-ucms btn-sm" type="button"
                                       data-id="status"
                                       data-action="hide"
                                       data-page-id="<?php echo $this->escape($page['id']);?>">
                                        <i class="icon-close"></i>
                                    </a>
                                <?php elseif($page['status'] == 0):?>
                                    <a class="btn btn-ucms btn-sm" type="button"
                                       data-id="status"
                                       data-action="show"
                                       data-page-id="<?php echo $this->escape($page['id']);?>">
                                        <i class="icon-check"></i>
                                    </a>
                                <?php endif;?>
                                <a class="btn btn-ucms btn-sm" type="button"
                                   data-id="status"
                                   data-action="delete"
                                   data-page-id="<?php echo  $page['id'];?>">
                                    <i class="icon-trash"></i>
                                </a>
                            </td>
                        </tr>
                    <?php endforeach; ?>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

<?php echo $this->htmlLibraries()->library('datatables'); ?>
<?php echo $this->modalBox('page'); ?>
<script>
<?php $this->inlineScript()->captureStart();?>
    $('#datatable').DataTable({
        lengthMenu: [[50, 100, -1], [50,100,"All"]],
        order: [1, 'asc'],
        columnDefs: [{
            targets: [0,1,4,-1],
            orderable: false,
            searchable: false
        }],
        "language": {
            "url": "http://cdn.datatables.net/plug-ins/1.10.13/i18n/Serbian.json"
        }
    });
<?php $this->inlineScript()->captureEnd();?>
</script>
