<!DOCTYPE html>
<!--[if IE 8]> <html lang="en" class="ie8 no-js"> <![endif]-->
<!--[if IE 9]> <html lang="en" class="ie9 no-js"> <![endif]-->
<!--[if !IE]><!-->
<html lang="en">
<!--<![endif]-->
<head>
    <meta charset="utf-8" />
    <title>G-CMS | Dashboard</title>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta content="width=device-width, initial-scale=1" name="viewport" />
    <meta content="" name="description" />
    <meta content="" name="author" />
    <!-- BEGIN GLOBAL MANDATORY STYLES -->
    <link href="http://fonts.googleapis.com/css?family=Open+Sans:400,300,600,700&subset=all" rel="stylesheet" type="text/css" />
    <link href="<?php echo $this->baseUrl('/skins/backend/global/plugins/font-awesome/css/font-awesome.min.css');?>" rel="stylesheet" type="text/css" />
    <link href="<?php echo $this->baseUrl('/skins/backend/global/plugins/simple-line-icons/simple-line-icons.min.css');?>" rel="stylesheet" type="text/css" />
    <link href="<?php echo $this->baseUrl('/skins/backend/global/plugins/bootstrap/css/bootstrap.min.css');?>" rel="stylesheet" type="text/css" />
    <link href="<?php echo $this->baseUrl('/skins/backend/global/plugins/bootstrap-switch/css/bootstrap-switch.min.css');?>" rel="stylesheet" type="text/css" />
    <link href="<?php echo $this->baseUrl('/skins/backend/global/css/components.css');?>" rel="stylesheet" id="style_components" type="text/css" />
    <link href="<?php echo $this->baseUrl('/skins/backend/global/css/plugins.min.css');?>" rel="stylesheet" type="text/css" />
    <link href="<?php echo $this->baseUrl('/skins/backend/layouts/layout/css/layout.min.css');?>" rel="stylesheet" type="text/css" />
    <link href="<?php echo $this->baseUrl('/skins/backend/layouts/layout/css/themes/default.min.css');?>" rel="stylesheet" type="text/css" id="style_color" />
    <link href="<?php echo $this->baseUrl('/skins/backend/cms/css/layouts.css');?>" rel="stylesheet" type="text/css">
    <link href="<?php echo $this->baseUrl('/skins/backend/cms/css/wizard.css');?>" rel="stylesheet" type="text/css">
    <link rel="shortcut icon" href="<?php echo $this->baseUrl('/skins/backend/favicon.ico');?>" />
    <link href="<?php echo $this->baseUrl('/skins/backend/cms/css/custom.css');?>" rel="stylesheet" type="text/css">
    <?php
    echo $this->headTitle();
    echo $this->headScript();
    echo $this->headLink();
    echo $this->headMeta();
    echo $this->headStyle();
    ?>
</head>

<body class="page-header-fixed page-sidebar-closed-hide-logo page-content-white">
    <div class="page-wrapper">

        <div class="page-header navbar navbar-fixed-top">
            <!-- BEGIN HEADER INNER -->
            <div class="page-header-inner ">
                <!-- BEGIN LOGO -->
                <div class="page-logo">
                    <a href="">
                        <!--<img src="assets/layouts/layout/img/logo.png" alt="logo" class="logo-default" />-->
                    </a>
                </div>
                <!-- END LOGO -->
                <a href="javascript:;" class="menu-toggler responsive-toggler" data-toggle="collapse" data-target=".navbar-collapse">
                    <span></span>
                </a>
                <div class="top-menu" style="float: left;">
                    <div class="nav navbar-nav pull-left">
                        <li class="dropdown dropdown-extended dropdown-inbox" id="header_inbox_bar">
                            <a href="javascript:;" class="dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-close-others="true">
                                <i class="icon-home"></i>
                            </a>
                        </li>
                    </div>
                </div>

                <div class="top-menu">
                    <ul class="nav navbar-nav pull-right">

                        <?php echo $this->getHelper('Dashboard')->language(); ?>

                        <li class="dropdown dropdown-user">
                            <a href="javascript:;" class="dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-close-others="true">
                                <img alt="" class="img-circle" src="assets/layouts/layout/img/avatar3_small.jpg" />
                                <span class="username username-hide-on-mobile"> Djordje </span>
                                <i class="fa fa-angle-down"></i>
                            </a>
                            <ul class="dropdown-menu dropdown-menu-default">
                                <li>
                                    <a href="">
                                        <i class="icon-user"></i> My Profile </a>
                                </li>
                                <li>
                                    <a href="">
                                        <i class="icon-calendar"></i> My Calendar </a>
                                </li>
                                <li>
                                    <a href="">
                                        <i class="icon-envelope-open"></i> My Inbox
                                        <span class="badge badge-danger"> 3 </span>
                                    </a>
                                </li>
                                <li class="divider"> </li>
                                <li>
                                    <a href="">
                                        <i class="icon-key"></i> Log Out </a>
                                </li>
                            </ul>
                        </li>


                    </ul>
                </div>
            </div>
        </div>

        <div class="clearfix"> </div>

        <div class="page-container">
            <?php echo $this->getHelper('Dashboard')->sidebar(); ?>
            <div class="page-content-wrapper">
                <div class="page-content">
                    <?php echo $this->getHelper('Dashboard')->breadcrumbs(); ?>
                    <?php echo $this->layout()->content; ?>
                </div>
            </div>
        </div>

        <div class="page-footer">
            <div class="page-footer-inner"> <?php echo date('Y');?> © G-CMS |
                <a target="_blank" href="">Ђорђе Стојиљковић</a>
            </div>
            <div class="scroll-to-top">
                <i class="icon-arrow-up"></i>
            </div>
        </div>

    </div>
    <!--[if lt IE 9]>
    <script src="<?php echo $this->baseUrl('/skins/backend/global/plugins/respond.min.js');?>"></script>
    <script src="<?php echo $this->baseUrl('/skins/backend/global/plugins/excanvas.min.js');?>"></script>
    <script src="<?php echo $this->baseUrl('/skins/backend/global/plugins/ie8.fix.min.js');?>"></script>
    <![endif]-->
    <script src="<?php echo $this->baseUrl('/skins/backend/global/plugins/jquery.min.js');?>" type="text/javascript"></script>
    <script src="<?php echo $this->baseUrl('/skins/backend/global/plugins/bootstrap/js/bootstrap.min.js');?>" type="text/javascript"></script>
    <script src="<?php echo $this->baseUrl('/skins/backend/global/plugins/jquery-slimscroll/jquery.slimscroll.min.js');?>" type="text/javascript"></script>
    <script src="<?php echo $this->baseUrl('/skins/backend/global/plugins/jquery.blockui.min.js');?>" type="text/javascript"></script>
    <script src="<?php echo $this->baseUrl('/skins/backend/global/plugins/bootstrap-switch/js/bootstrap-switch.min.js');?>" type="text/javascript"></script>
    <script src="<?php echo $this->baseUrl('/skins/backend/global/scripts/app.min.js');?>" type="text/javascript"></script>
    <script src="<?php echo $this->baseUrl('/skins/backend/layouts/layout/scripts/layout.min.js');?>" type="text/javascript"></script>
    <script src="<?php echo $this->baseUrl('/skins/backend/layouts/layout/scripts/demo.min.js');?>" type="text/javascript"></script>
    <script src="<?php echo $this->baseUrl('/skins/backend/layouts/global/scripts/quick-sidebar.min.js');?>" type="text/javascript"></script>
    <script src="<?php echo $this->baseUrl('/skins/backend/layouts/global/scripts/quick-nav.min.js');?>" type="text/javascript"></script>

    <?php echo $this->inlineScript(); ?>
</body>
</html>