<h1 class="page-title"> Kategorije
    <small> Menadžment kategorija</small>
    <div class="btn-group pull-right btn-click-cms">
        <a class="btn sbold green"> Dodaj novu &nbsp;
            <i class="fa fa-plus"></i>
        </a>
    </div>
</h1>

<div class="row">
    <div class="col-md-12">
        <div class="portlet light bordered">
            <div class="portlet-title">
                <div class="caption font-dark">
                    <i class="icon-pin font-dark"></i>
                    <span class="caption-subject bold uppercase"> Lista kategorija</span>
                </div>
            </div>
            <div class="portlet-body">
                <table class="table table-striped table-bordered table-hover table-checkable order-column" id="datatable">
                    <thead>
                    <tr>
                        <th>

                        </th>
                        <th  class="text-center">
                            Naziv
                        </th>
                        <th  class="text-center">
                            Datum kreiranja
                        </th>
                        <th  class="text-center">
                            Status
                        </th>
                        <th class="text-center" style="width:1%;">Akcije</th>
                    </tr>
                    </thead>
                    <tbody>
                    <?php $i=0; foreach ($this->categories as $category): $i++;?>
                        <tr class="odd-gradeX">
                            <td><?php echo $i; ?></td>
                            <td  class="text-center"><?php echo $this->escape($category['name']); ?></td>
                            <td  class="text-center"><?php echo $this->escape(date('M d, Y', strtotime($category['date_created']))); ?></td>
                            <td class="text-center">
                                <?php if ($category['status'] == Model_Admin_Blog_BlogCategory::STATUS_VISIBLE):?>
                                    <span class="label label-sm label-info" style="background-color: #8775a7;"> Vidljivo </span>
                                <?php else:?>
                                    <span class="label label-sm label-danger label-info" style="background-color: #8775a7;"> Sakriveno </span>
                                <?php endif; ?>
                            </td>
                            <td class="text-center" style="width: 15%;">
                                <a  class="btn btn-ucms btn-sm" type="button"
                                    data-action="edit"
                                    data-category-id="<?php echo $this->escape($category['id']);?>">
                                    <i class="icon-pencil"></i>
                                </a>
                            <?php if ($category['status'] == 1):?>
                                <a class="btn btn-ucms btn-sm" type="button"
                                   data-id="status"
                                   data-action="hide"
                                   data-category-id="<?php echo $this->escape($category['id']);?>">
                                    <i class="icon-close"></i>
                                </a>
                            <?php elseif($category['status'] == 0):?>
                                <a class="btn btn-ucms btn-sm" type="button"
                                   data-id="status"
                                   data-action="show"
                                   data-category-id="<?php echo $this->escape($category['id']);?>">
                                    <i class="icon-check"></i>
                                </a>
                            <?php endif;?>
                                <a class="btn btn-ucms btn-sm" type="button"
                                   data-id="status"
                                   data-action="delete"
                                   data-category-id="<?php echo  $category['id'];?>">
                                    <i class="icon-trash"></i>
                                </a>
                            </td>
                        </tr>
                    <?php endforeach; ?>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

<?php echo $this->form; ?>

<?php echo $this->htmlLibraries()->library('datatables'); ?>
<?php echo $this->modalBox('category'); ?>

<script>
<?php $this->inlineScript()->captureStart();?>
    $('#datatable').DataTable({
        lengthMenu: [[50, 100, -1], [50,100,"All"]],
        order: [0, 'asc'],
        columnDefs: [{
            targets: [-1],
            orderable: false,
        }],
        "language": {
            "url": "http://cdn.datatables.net/plug-ins/1.10.13/i18n/Serbian.json"
        }
    });

    $('.btn-click-cms').on('click', function(e){
        e.preventDefault();
        e.stopPropagation();


        if ( $("[name='task']").length > 0) {
            $("[name='task']").remove();
            $("[name='id']").remove();
        }

        createInput('task', 'create');

        $("[name='name']").val('');
        $('#submit').text('Kreiraj');
        $('#categorycreate').modal('show');
    });

    $('[data-action="edit"]').on('click', function (e) {
        var parent = $(this).is('[data-action="edit"]') ? $(this) : $(this).closest('[data-id="edit"]');
        var categoryId = parent.attr('data-category-id');

        $.ajax({
            url: '<?php echo $this->url(array('controller' => 'admin_blog', 'action' => 'category')) ;?>',
            method: 'post',
            data:  {
                categoryId: categoryId
            },
        }).done(function(data) {

            $('input[name="name"]').attr('value', data);
            $('input[name="name"]').val(data);

            if ( $("[name='task']").length > 0) {
                $("[name='task']").remove();
                $("[name='id']").remove();
            }

            createInput('task', 'update');
            createInput('id', categoryId);

            $('#submit').text('Ažuriraj');
            $('#categorycreate').modal('show');

        }).fail(function() {
            console.log('There was error while communicated with server.');
        });

    });

    function createInput(name, value) {
        var input = document.createElement("input");
        input.setAttribute("type", "hidden");
        input.setAttribute("name", name);
        input.setAttribute("value", value);
        document.getElementById("createupdate").appendChild(input);
        return input;
    }

<?php $this->inlineScript()->captureEnd();?>
</script>
