<h1 class="page-title"> Oznake
    <small> Menadžment oznaka</small>
    <div class="btn-group pull-right btn-click-cms">
        <a class="btn sbold green"> Dodaj novu &nbsp;
            <i class="fa fa-plus"></i>
        </a>
    </div>
</h1>

<div class="row">
    <div class="col-md-12">
        <div class="portlet light bordered">
            <div class="portlet-title">
                <div class="caption font-dark">
                    <i class="icon-pin font-dark"></i>
                    <span class="caption-subject bold uppercase"> Lista oznaka</span>
                </div>
            </div>
            <div class="portlet-body">
                <table class="table table-striped table-bordered table-hover table-checkable order-column" id="datatable">
                    <thead>
                    <tr>
                        <th>

                        </th>
                        <th  class="text-center">
                            Naziv
                        </th>
                        <th  class="text-center">
                            Objava
                        </th>
                        <th class="text-center" style="width:1%;">Akcije</th>
                    </tr>
                    </thead>
                    <tbody>
                    <?php $i=0; foreach ($this->tags as $tag): $i++;?>
                        <tr class="odd-gradeX">
                            <td><?php echo $i; ?></td>
                            <td  class="text-center"><?php echo $this->escape($tag['title']); ?></td>
                            <td></td>
                            <td class="text-center" style="width: 15%;">
                                <a  class="btn btn-ucms btn-sm" type="button"
                                    data-action="edit"
                                    data-tag-id="<?php echo $this->escape($tag['id']);?>">
                                    <i class="icon-pencil"></i>
                                </a>
                                <a class="btn btn-ucms btn-sm" type="button"
                                   data-id="status"
                                   data-action="delete"
                                   data-tag-id="<?php echo  $tag['id'];?>">
                                    <i class="icon-trash"></i>
                                </a>
                            </td>
                        </tr>
                    <?php endforeach; ?>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

<?php echo $this->form; ?>

<?php echo $this->htmlLibraries()->library('datatables'); ?>
<?php echo $this->modalBox('tag'); ?>

<script>
    <?php $this->inlineScript()->captureStart();?>
    $('#datatable').DataTable({
        lengthMenu: [[50, 100, -1], [50,100,"All"]],
        order: [0, 'asc'],
        columnDefs: [{
            targets: [0, -1],
            orderable: false,
        }],
        "language": {
            "url": "http://cdn.datatables.net/plug-ins/1.10.13/i18n/Serbian.json"
        }
    });

    $('.btn-click-cms').on('click', function(e){
        e.preventDefault();
        e.stopPropagation();


        if ( $("[name='task']").length > 0) {
            $("[name='task']").remove();
            $("[name='id']").remove();
        }

        createInput('task', 'create');

        $("[name='title']").val('');
        $('#submit').text('Kreiraj');
        $('#tagcreate').modal('show');
    });

    $('[data-action="edit"]').on('click', function (e) {
        var parent = $(this).is('[data-action="edit"]') ? $(this) : $(this).closest('[data-id="edit"]');
        var tagId = parent.attr('data-tag-id');

        $.ajax({
            url: '<?php echo $this->url(array('controller' => 'admin_blog', 'action' => 'tag')) ;?>',
            method: 'post',
            data:  {
                tagId: tagId
            },
        }).done(function(data) {

            $('input[name="title"]').attr('value', data);
            $('input[name="title"]').val(data);

            if ( $("[name='task']").length > 0) {
                $("[name='task']").remove();
                $("[name='id']").remove();
            }

            createInput('task', 'update');
            createInput('id', tagId);

            $('#submit').text('Ažuriraj');
            $('#tagcreate').modal('show');

        }).fail(function() {
            console.log('There was error while communicated with server.');
        });

    });

    function createInput(name, value) {
        var input = document.createElement("input");
        input.setAttribute("type", "hidden");
        input.setAttribute("name", name);
        input.setAttribute("value", value);
        document.getElementById("createupdate").appendChild(input);
        return input;
    }

    <?php $this->inlineScript()->captureEnd();?>
</script>

