<?php $option = $this->element->getDecorator('ViewScript')->getOptions(); ?>
<form class="layout"
      method="<?php echo $this->element->getMethod();?>"
      action="<?php echo $this->element->getAction();?>"
      id="createupdate">

    <div class="modal fade in" id="tagcreate">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true"></button>
                    <h4 class="modal-title">Nova oznaka</h4>
                </div>

                <div class="modal-body">
                    <div class="row">
                        <div class="col-md-12">
                            <label class="control-label">Ime oznake</label>
                            <?php echo $this->element->title; ?>
                        </div>
                    </div>
                </div>

                <div class="modal-footer">
                    <button type="button" class="btn dark btn-outline" data-dismiss="modal">Zatvori</button>
                    <button type="submit" class="btn green" id="submit">Kreiraj</button>
                </div>
            </div>
        </div>
    </div>

</form>