<?php

class Admin_MultimediaController extends Zend_Controller_Action
{
    public function init()
    {
        $this->_helper->viewRenderer->setNoRender(TRUE);
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function indexAction()
    {

    }

    public function createAction()
    {

    }
}