<?php

class Admin_SliderController extends Zend_Controller_Action
{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function indexAction()
    {

    }

    public function createAction()
    {

    }
}